# Generated by Django 4.2.2 on 2023-06-22 15:16

from django.db import migrations
from django.core.management import call_command
from django.db.migrations import RunPython


def func(apps, schema_editor):
    call_command('loaddata', 'todo_list_data.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(func, reverse_func),
    ]

